import { L as Base, type Label } from "@/lib/labels";

/** S2-only labels on top of the shared set. */
export const L = {
  ...Base,
  naya: { roman: "+ Naya", en: "New", ur: "نیا" },
  name: { roman: "Naam", en: "Name", ur: "نام" },
  photo: { roman: "Tasveer", en: "Photo", ur: "تصویر" },
  camera: { roman: "Camera", en: "Camera", ur: "کیمرہ" },
  gallery: { roman: "Gallery", en: "Upload", ur: "گیلری" },
  voice: { roman: "Awaaz", en: "Voice memo", ur: "آواز" },
  holdToRecord: { roman: "Daba ke Bolo", en: "Hold to record", ur: "دبا کر بولیں" },
  recording: { roman: "Bol Rahe Hain…", en: "Recording…", ur: "ریکارڈ ہو رہا ہے" },
  costPrice: { roman: "Khareed", en: "Cost", ur: "خرید" },
  minPrice: { roman: "Kam Se Kam", en: "Min price", ur: "کم سے کم" },
  openingStock: { roman: "Shuru ka Stock", en: "Opening stock", ur: "شروع کا اسٹاک" },
  currentStock: { roman: "Abhi Stock", en: "Current stock", ur: "ابھی اسٹاک" },
  lowAlert: { roman: "Kam Hone Par Batao", en: "Low-stock alert", ur: "کم ہونے پر بتائیں" },
  newItem: { roman: "Nayi Cheez", en: "New item", ur: "نئی چیز" },
  saved: { roman: "Ho Gaya!", en: "Saved", ur: "ہو گیا" },
  bulkEdit: { roman: "Sab Badlo", en: "Bulk edit", ur: "سب بدلیں" },
  saveAll: { roman: "Sab Save Karo", en: "Save all", ur: "سب محفوظ کریں" },
  increase: { roman: "Rate Barhao", en: "Increase prices", ur: "ریٹ بڑھائیں" },
  allItems: { roman: "Sab Cheezein", en: "All items", ur: "سب چیزیں" },
  adjustment: { roman: "Ginti Theek", en: "Adjustment", ur: "گنتی ٹھیک" },
  returnLbl: { roman: "Wapsi", en: "Return", ur: "واپسی" },
  notes: { roman: "Note", en: "Notes", ur: "نوٹ" },
  invoiceNo: { roman: "Bill #", en: "Invoice no", ur: "بل نمبر" },
  date: { roman: "Tareekh", en: "Date", ur: "تاریخ" },
  type: { roman: "Kaam", en: "Type", ur: "قسم" },
  pooraCash: { roman: "Poora Cash", en: "Paid in full", ur: "پورا کیش" },
  kuchCash: { roman: "Kuch Cash", en: "Part cash", ur: "کچھ کیش" },
  newStock: { roman: "Naya Stock", en: "New stock", ur: "نیا اسٹاک" },
  another: { roman: "Aur Maal", en: "New purchase", ur: "اور مال" },
  grahak: { roman: "Grahak", en: "Customers", ur: "گاہک" },
  bapaari: { roman: "Bapaari", en: "Suppliers", ur: "بیوپاری" },
  newParty: { roman: "+ Naya Party", en: "New party", ur: "نئی پارٹی" },
  phone: { roman: "Phone", en: "Phone", ur: "فون" },
  creditLimit: { roman: "Udhaar Hadd", en: "Credit limit", ur: "ادھار حد" },
  overLimit: { roman: "Udhaar Hadd Se Zyada!", en: "Over credit limit", ur: "ادھار حد سے زیادہ" },
  vasooli: { roman: "Vasooli Record Karein", en: "Record payment received", ur: "وصولی ریکارڈ کریں" },
  adaigi: { roman: "Adaigi Karein", en: "Make payment", ur: "ادائیگی کریں" },
  reminder: { roman: "Yaad Dilao", en: "WhatsApp reminder", ur: "یاد دلائیں" },
  call: { roman: "Call", en: "Call", ur: "کال" },
  ledger: { roman: "Hisaab", en: "Ledger", ur: "حساب" },
  opening: { roman: "Purana Hisaab", en: "Opening balance", ur: "پرانا حساب" },
  clear: { roman: "Barabar", en: "Settled", ur: "برابر" },
  pickItem: { roman: "Cheez Chuno", en: "Pick an item", ur: "چیز چنیں" },
  pickParty: { roman: "Party Chuno", en: "Pick a party", ur: "پارٹی چنیں" },
} satisfies Record<string, Label>;
