import { L, type Label } from "@/lib/labels";

/** S3 labels: shared L plus Sales & Cash words. */
export const S = {
  ...L,
  savePrint: { roman: "SAVE & PRINT", en: "Save & Print", ur: "محفوظ اور پرنٹ" },
  walkIn: { roman: "Gahak ka Naam", en: "Walk-in name", ur: "گاہک کا نام" },
  chooseCustomer: { roman: "Gahak Chuno", en: "Pick customer", ur: "گاہک چنیں" },
  received: { roman: "Naqd Mile", en: "Cash Received", ur: "نقد ملے" },
  full: { roman: "Poora", en: "Full", ur: "پورا" },
  change: { roman: "Wapis Do", en: "Change", ur: "واپس دیں" },
  subtotal: { roman: "Jama", en: "Subtotal", ur: "جمع" },
  lowRate: { roman: "Rate Kam Hai!", en: "Below min price", ur: "ریٹ کم ہے" },
  needParty: { roman: "Udhaar ke liye Gahak Chuno", en: "Credit needs a customer", ur: "ادھار کے لیے گاہک چنیں" },
  emptyCart: { roman: "Cheez Chuno", en: "Tap items to add", ur: "چیز چنیں" },
  ok: { roman: "Theek Hai", en: "OK", ur: "ٹھیک ہے" },
  quotations: { roman: "Purane Andaze", en: "Saved Quotations", ur: "پرانے اندازے" },
  newQuotation: { roman: "Naya Andaza", en: "New Quotation", ur: "نیا اندازہ" },
  pukkaBill: { roman: "Pukka Bill Banao", en: "Convert to Sale", ur: "پکا بل بنائیں" },
  converted: { roman: "Bill Ban Gaya", en: "Converted", ur: "بل بن گیا" },
  invoices: { roman: "Purane Bill", en: "Invoices", ur: "پرانے بل" },
  whatsapp: { roman: "WhatsApp", en: "WhatsApp", ur: "واٹس ایپ" },
  savePdf: { roman: "PDF Banao", en: "Save PDF", ur: "پی ڈی ایف" },
  pdfHint: { roman: "Printer mein 'Save as PDF' chuno", en: "Choose 'Save as PDF' as printer", ur: "پرنٹر میں پی ڈی ایف چنیں" },
  all: { roman: "Sab", en: "All", ur: "سب" },
  from: { roman: "Se", en: "From", ur: "سے" },
  to: { roman: "Tak", en: "To", ur: "تک" },
  date: { roman: "Tareekh", en: "Date", ur: "تاریخ" },
  amount: { roman: "Raqam", en: "Amount", ur: "رقم" },
  description: { roman: "Tafseel", en: "Description", ur: "تفصیل" },
  newBalance: { roman: "Ab Khata", en: "New balance", ur: "اب کھاتہ" },
  chai: { roman: "Chai", en: "Tea", ur: "چائے" },
  tankhwah: { roman: "Tankhwah", en: "Salary", ur: "تنخواہ" },
  kiraya: { roman: "Kiraya", en: "Rent", ur: "کرایہ" },
  bijli: { roman: "Bijli", en: "Electricity", ur: "بجلی" },
  carriage: { roman: "Carriage", en: "Carriage", ur: "کیرج" },
  other: { roman: "Other", en: "Other", ur: "دیگر" },
  subahCash: { roman: "Subah ka Cash", en: "Opening Cash", ur: "صبح کا کیش" },
  cashInDay: { roman: "Cash Aaya", en: "Cash In", ur: "کیش آیا" },
  cashOutDay: { roman: "Cash Gaya", en: "Cash Out", ur: "کیش گیا" },
  closing: { roman: "Shaam ka Cash", en: "Closing Cash", ur: "شام کا کیش" },
  fromYesterday: { roman: "Kal se", en: "From yesterday", ur: "کل سے" },
  cashInHand: { roman: "Galla", en: "Cash in Hand", ur: "گلہ" },
  todaySale: { roman: "Aaj ki Sale", en: "Today's Sales", ur: "آج کی سیل" },
  munafa: { roman: "Munafa", en: "Profit", ur: "منافع" },
  nuqsan: { roman: "Nuqsan", en: "Loss", ur: "نقصان" },
  thisMonth: { roman: "Is Mahine", en: "This Month", ur: "اس مہینے" },
  paper: { roman: "Kaghaz", en: "Paper", ur: "کاغذ" },
  back: { roman: "Wapis", en: "Back", ur: "واپس" },
  thanks: { roman: "Shukriya", en: "Thank you", ur: "شکریہ" },
  bill: { roman: "Bill", en: "Sale", ur: "بل" },
} satisfies Record<string, Label>;
